// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1up6Kk1tGLS57fcVgWpbPWEoNhL5gAIM',
    appId: '1:200669196263:web:f9533206cb04c3e2b05742',
    messagingSenderId: '200669196263',
    projectId: 'panchikawatta-d9e2e',
    authDomain: 'panchikawatta-d9e2e.firebaseapp.com',
    storageBucket: 'panchikawatta-d9e2e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg8gUhnbgogRFfktoF7TZB1k1wfs5OxHQ',
    appId: '1:200669196263:android:287ecaa5c94e5d4cb05742',
    messagingSenderId: '200669196263',
    projectId: 'panchikawatta-d9e2e',
    storageBucket: 'panchikawatta-d9e2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD69DCId-nbbDvaiWrxP8vjTuVHUIrtD9I',
    appId: '1:200669196263:ios:5efcc1bebb8e0048b05742',
    messagingSenderId: '200669196263',
    projectId: 'panchikawatta-d9e2e',
    storageBucket: 'panchikawatta-d9e2e.appspot.com',
    iosBundleId: 'com.example.panchikawatta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD69DCId-nbbDvaiWrxP8vjTuVHUIrtD9I',
    appId: '1:200669196263:ios:5efcc1bebb8e0048b05742',
    messagingSenderId: '200669196263',
    projectId: 'panchikawatta-d9e2e',
    storageBucket: 'panchikawatta-d9e2e.appspot.com',
    iosBundleId: 'com.example.panchikawatta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1up6Kk1tGLS57fcVgWpbPWEoNhL5gAIM',
    appId: '1:200669196263:web:b08edd918f7306cdb05742',
    messagingSenderId: '200669196263',
    projectId: 'panchikawatta-d9e2e',
    authDomain: 'panchikawatta-d9e2e.firebaseapp.com',
    storageBucket: 'panchikawatta-d9e2e.appspot.com',
  );
}
